### PR TITLE
Use chpasswd instead of passwd

### PR DESCRIPTION
**Pull request by lurch**
https://github.com/raspberrypi-ui/piwiz/pull/11 ported to this repo :wink:

### CODE REVIEW

**Comment by XECDesign** [comment]
Out of curiosity, what difference does this make?

**Comment by lurch** [comment]
Just makes the code a little bit simpler. And https://stackoverflow.com/questions/714915/using-the-passwd-command-from-within-a-shell-script suggests it might be more reliable?

**Comment by XECDesign** [comment]
ah, nice.

**Comment by spl237** [comment]
Merged - many thanks!

**Pull request merged**
